{{
  config(
    materialized='table'
  )
}}

WITH servicing_cte AS (
 SELECT 
   SERVICINGLENDERNAME
	SERVICINGLENDERADDRESS
    SERVICINGLENDERCITY
    SERVICINGLENDERSTATE,
    SERVICINGLENDERZIP,
from DATA;
);

INSERT INTO DIM_SERVICINGLENDER (SERVICINGLENDERNAME, SERVICINGLENDERADDRESS, SERVICINGLENDERCITY, SERVICINGLENDERSTATE, SERVICINGLENDERZIP)
SELECT DISTINCT SERVICINGLENDERNAME, SERVICINGLENDERADDRESS, SERVICINGLENDERCITY, SERVICINGLENDERSTATE, SERVICINGLENDERZIP 
FROM servicing_cte
    
    
    