{{
  config(
    materialized='table'
  )
}}

WITH originating_cte AS (
 SELECT 
    ORIGINATINGLENDERLOCATIONID,
	ORIGINATINGLENDER    ,
	ORIGINATINGLENDERCITY ,
	ORIGINATINGLENDERSTATE
from DATA;
);

INSERT INTO DIM_ORIGINATINGLENDER (ORIGINATINGLENDERLOCATIONID, ORIGINATINGLENDER, ORIGINATINGLENDERCITY, ORIGINATINGLENDERSTATE)
SELECT DISTINCT ORIGINATINGLENDERLOCATIONID, ORIGINATINGLENDER, ORIGINATINGLENDERCITY, ORIGINATINGLENDERSTATE
FROM originating_cte
   