{{
  config(
    materialized='table'
  )
}}

WITH borrower_cte AS (
 SELECT DISTINCT

    BORROWNAME,
	BORROWERADDRESS,
	BORROWERCITY ,
	BORROWERSTATE,
	BORROWERZIP,
	BUSINESSAGEDESCRIPTION   ,
	RACE     ,
	ETHNICITY     ,
	GENDER     ,
	VETERAN     ,
	NONPROFIT     ,
	FRANCHISENAME     ,
	BUSINESSTYPE    ,

from DATA;
);

INSERT INTO dim_borrower(BORROWNAME, BORROWERADDRESS, BORROWERCITY, BORROWERSTATE, BORROWERZIP, BUSINESSAGEDESCRIPTION, RACE, ETHNICITY, GENDER, VETERAN, NONPROFIT, FRANCHISENAME, BUSINESSTYPE)
SELECT BORROWNAME, BORROWERADDRESS, BORROWERCITY, BORROWERSTATE, BORROWERZIP, BUSINESSAGEDESCRIPTION, RACE, ETHNICITY, GENDER, VETERAN, NONPROFIT, FRANCHISENAME, BUSINESSTYPE
FROM borrower_cte
